import './globals.css';
import Header from '@/app/components/Header';
import ThemeCom from '@/app/components/ThemeCom';
import { ClerkProvider } from '@clerk/nextjs';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang='en' suppressHydrationWarning>
        <body>
          <ThemeCom>
            <Header />
            {children}
          </ThemeCom>
        </body>
      </html>
    </ClerkProvider>
  );
}
